fix:changed to grid layout
varun-Tad/PowerUI pull request #5
Opened 2022-02-05 05:40 UTC by varun-Tad

Created images and inputs

2022-02-05 06:51 UTC, gauravsinhaweb commented
https://user-images.githubusercontent.com/75125943/152631913-b7968d1d-fbc2-42d6-aa2a-1e497d5f3426.mp4

the website zoom in, in mobile responsive, to avoid that you can add content width to 100%. ```     <meta name="viewport" content="width=100%" />
```
nice work done!

2022-02-05 08:56 UTC, Ankur9669 requested changes

2022-02-05 08:56 UTC, Ankur9669 commented on Components/Alerts/alerts.css
>      text-align: center;
You could use max-width here than your alert would become responsive. But that's just a suggestio this also looks fine.

2022-02-05 08:56 UTC, Ankur9669 commented on Components/Badges/badge.css
![image](https://user-images.githubusercontent.com/65125998/152635022-ae92bf08-d91a-4c28-bb59-63609e19691e.png)
1. See you are repeating the code border-radius 50% AND font-weight so you can creat a class 
badge{
    border-radius: 50%;
    font-weight:700;
}
And use it everywhere. This also looks good by the way

2022-02-05 08:56 UTC, Ankur9669 commented on Components/Buttons/buttons.css
> -    padding:15px;
Try to use css variable here

2022-02-05 08:56 UTC, Ankur9669 commented on Components/Buttons/buttons.css
>  }
![image](https://user-images.githubusercontent.com/65125998/152635166-67174192-5dfc-4f3d-ac6a-a9ffc864bbc7.png)
You have used hover properties but see all the hover are using same opacity:0.7
So you can just do 
.btn:hover{
     opacity:0.7
}
And then you can safely remove other classes

2022-02-05 08:56 UTC, Ankur9669 commented on Components/Image/image.css
> +    border-radius: 50%;
You can give rems here if you want

2022-02-05 08:56 UTC, Ankur9669 commented on Components/Input/input.css
> +
All the input boxes have same width, padding and border-radius but you have repeated them in 3 places. So try to creat a utility class.

2022-02-06 21:30 UTC, varun-Tad commented
Thanks for the review guys.I have made all the changes @Ankur9669 @gauravsinhaweb

2022-02-06 21:31 UTC, merged